Suppress tracebacks.
agronholm/typeguard pull request #106
Opened 2020-01-04 00:38 UTC by prescod

Suppress extra lines in tracebacks as per the comment:

# suppress unnecessarily long tracebacks

2021-01-19 19:01 UTC, prescod commented
@agronholm Should I update this? Other than the conflicts, is it the correct implementation?

2021-01-20 07:37 UTC, agronholm requested changes
Changes needed – I'll merge once you've made them.

2021-01-20 07:37 UTC, agronholm commented on tests/test_typeguard.py
> +        try:
Separate logical blocks with an empty line.

2021-01-20 07:37 UTC, agronholm commented on typeguard/__init__.py
> +            raise TypeError(exc) from None
Use `**exc.args` as argument. Using the previous exception as argument makes the exception look like this: `TypeError(TypeError('argument "a" must be a callable',),)`

2021-01-20 07:37 UTC, agronholm commented on typeguard/__init__.py
> +                raise TypeError(exc) from None
As above.

2021-01-20 07:37 UTC, agronholm commented on typeguard/__init__.py
> +            raise TypeError(exc) from None
Ditto.

2021-01-20 07:37 UTC, agronholm commented on tests/test_typeguard.py
> +import traceback
Don't interleave "from" imports and direct imports. Move this to the top.

2021-01-24 13:43 UTC, agronholm approved these changes

2021-01-24 13:50 UTC, merged

2021-01-24 13:50 UTC, agronholm commented
Thanks!