make typeguard work on python3.9
agronholm/typeguard pull request #150
Opened 2020-10-07 00:11 UTC by deathowl

Add python 3.9 to tox.ini
make tests pass for 3.9 as well as other supported python versions
fix #149

2020-10-07 00:36 UTC, deathowl commented
sorry for the python3.9-dev in the travis.yml can be replaced with non-dev 3.9 once travis makes it available

2020-10-07 07:23 UTC, agronholm requested changes
Mostly code style changes requested. Seems good otherwise.

2020-10-07 07:23 UTC, agronholm commented on typeguard/__init__.py
> +    expected_class = expected_type.__args__[0] if hasattr(
If a tertiary expression has to be split to multiple lines then it should be converted to a real "if" block.

2020-10-07 07:23 UTC, agronholm commented on typeguard/__init__.py
> +        rtype_args = memo.type_hints['return'].__args__ if hasattr(
Same here.

2020-10-07 07:23 UTC, agronholm commented on typeguard/__init__.py
> +        if hasattr(expected_type, "__args__") and expected_type.__args__ not in \
Parentheses are preferred over splitting lines with a backslash.

2020-10-07 07:23 UTC, agronholm commented on typeguard/__init__.py
> +    if hasattr(expected_type, "__args__") and expected_type.__args__:
`if getattr(expected_type, '__args__', None):`

2020-10-07 12:12 UTC, deathowl commented on tests/test_typeguard.py
> -from typing_extensions import NoReturn, Protocol, Literal, TypedDict, runtime_checkable
```
Python 3.9.0 (default, Oct  6 2020, 10:37:47)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing_extensions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'typing_extensions'
```

2020-10-07 23:13 UTC, deathowl commented on tests/test_typeguard.py
> -from typing_extensions import NoReturn, Protocol, Literal, TypedDict, runtime_checkable
ok, removed and still works fine, i was just overly cautious

2020-10-08 15:21 UTC, deathowl commented
@agronholm  addressed your requests.

2020-10-08 17:05 UTC, agronholm approved these changes

2020-10-08 17:17 UTC, agronholm commented
I screwed up the build. I'll fix that before I merge.

2020-10-08 17:27 UTC, merged

2020-10-08 17:27 UTC, agronholm commented
Thanks!

2020-10-08 17:27 UTC, deathowl commented
btw what is your opinion on using black to automate code formatting in the future?

2020-10-08 17:35 UTC, agronholm commented
Over my rotting corpse.

2020-10-12 19:41 UTC, leycec commented
⮤ This is the only valid response to that question.

2020-10-19 07:20 UTC, shadchin commented
Can you upload to PyPI release with support Python 3.9?

2020-10-19 08:12 UTC, agronholm commented
I tried...but it seems some changes on Travis have broken my workflow. It ended uploading typeguard-0.0.0 to PyPI :(

2020-10-19 08:15 UTC, agronholm commented
Scratch that, it was the continued modernization of setup.py.

2020-10-19 08:19 UTC, agronholm commented
Done, it's now on PyPI.