Add decorator to disable run time type checking
agronholm/typeguard pull request #180
Opened 2021-03-16 19:04 UTC by cjolowicz

Closes #179

2021-03-19 12:13 UTC, agronholm commented
Looking good so far. I'll do a more thorough pass this weekend and merge if I see no issues.

2021-03-19 17:24 UTC, agronholm requested changes
Ok, this is an elegant solution! If you could also add a changelog entry, I'll merge right away then.

2021-03-19 17:38 UTC, agronholm approved these changes

2021-03-19 18:34 UTC, merged

2021-03-19 18:34 UTC, agronholm commented
Thanks a lot! This was perfect work.

2021-03-19 19:23 UTC, cjolowicz commented
Thank you for merging this @agronholm :)

2022-01-06 13:21 UTC, JeroenBos commented
Thank you for implementing this decorator. I was keen to remove my workaround when updating `typeguard`, however, I realize that this decorator is not as versatile as I had hoped.

I was hoping that this decorator could be useful e.g. to prevent a `TypeError` from being raised when testing that certain errors are thrown, e.g.
```python
import unittest
class TestErrors(unittest.TestCase):
    def test_that_arg_of_wrong_type_raises(self):
        with typeguard_ignore(some_method):  # or ignore_typeguard_on from below
            with self.assertRaises(ValueError):
                some_method(some_wrong_value)

```

The idea being that normally typeguards are in effect, except under certain test conditions.

For full information, also to others that might have the same question, this is the workaround I had:

```python
from contextlib import contextmanager
from typing import Any
from unittest.mock import patch
from weakref import WeakKeyDictionary

@contextmanager
def ignore_typeguard_on(any: Any):
    """
    A helper to disable typeguard on the specified object,
    for when you explicitly want to pass in wrongly typed objects.
    """

    # disable a cache employed by typeguard:
    with patch("typeguard._type_hints_map", WeakKeyDictionary()):

        # set all annotations temporarily to typing.Any
        annotations = getattr(any, "__annotations__", None)
        if annotations is not None:
            with patch.dict(annotations, {key: Any for key in annotations.keys()}):
                yield
        else:
            yield
```